/*
 * This file is part of RadPlanBio
 *
 * Copyright (C) 2013-2016 Tomas Skripcak
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package de.dktk.dd.rpb.participate.web.util;

import static javax.faces.application.FacesMessage.SEVERITY_ERROR;
import static javax.faces.application.FacesMessage.SEVERITY_FATAL;
import static javax.faces.application.FacesMessage.SEVERITY_INFO;
import static javax.faces.application.FacesMessage.SEVERITY_WARN;

import javax.faces.application.FacesMessage;
import javax.faces.application.FacesMessage.Severity;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import de.dktk.dd.rpb.participate.web.util.ExceptionUtil;
import org.apache.log4j.Logger;
import org.springframework.context.annotation.Lazy;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.dao.OptimisticLockingFailureException;
import org.springframework.security.access.AccessDeniedException;

import de.dktk.dd.rpb.core.domain.Identifiable;
import de.dktk.dd.rpb.core.util.ResourcesUtil;

/**
 * Message utility for which helps to create info/warn/error messages in JSF controllers
 * Business exceptions can be mapped to user friendly messages inside the error (Exception err) method.
 *
 * @author initial source code generated by Celerio, a Jaxio product
 */
@Named
@Singleton
@Lazy(false)
public class MessageUtil {

    //region Finals

    private static final Logger log = Logger.getLogger(MessageUtil.class);

    //endregion

    //region Injects

    @Inject
    private ResourcesUtil resourcesUtil;

    //endregion

    //region Properties

    public ResourcesUtil getResourcesUtil() {
        return this.resourcesUtil;
    }

    //endregion

    //region Singleton

    private static MessageUtil instance;

    public MessageUtil() {
        instance = this;
    }

    public static MessageUtil getInstance() {
        return instance;
    }

    //endregion

    //region Methods

    //region Info

    public void info(String summaryKey, Object... args) {
        addFacesMessageUsingKey(SEVERITY_INFO, summaryKey, args);
    }

    public void infoEntity(String summaryKey, Identifiable<?> entity) {
        addFacesMessageUsingKey(SEVERITY_INFO, summaryKey, entity.toString());
    }

    @SuppressWarnings("unused")
    public void infoText(String summaryText) {
        addFacesMessageUsingText(SEVERITY_INFO, summaryText);
    }

    @SuppressWarnings("unused")
    public FacesMessage newInfo(String summaryKey, Object... args) {
        return newFacesMessageUsingKey(SEVERITY_INFO, summaryKey, args);
    }

    //endregion

    // region Warning

    public void warning(String summaryKey, Object... args) {
        addFacesMessageUsingKey(SEVERITY_WARN, summaryKey, args);
    }

    @SuppressWarnings("unused")
    public void warningText(String summaryText) {
        addFacesMessageUsingText(SEVERITY_WARN, summaryText);
    }

    @SuppressWarnings("unused")
    public FacesMessage newWarning(String summaryKey, Object... args) {
        return newFacesMessageUsingKey(SEVERITY_WARN, summaryKey, args);
    }

    //endregion

    //region Error

    public void error(String summaryKey, Object... args) {
        addFacesMessageUsingKey(SEVERITY_ERROR, summaryKey, args);
    }

    @SuppressWarnings("unused")
    public void errorText(String summaryText) {
        addFacesMessageUsingText(SEVERITY_ERROR, summaryText);
    }

    @SuppressWarnings("unused")
    public FacesMessage newError(String summaryKey, Object... args) {
        return newFacesMessageUsingKey(SEVERITY_ERROR, summaryKey, args);
    }

    /**
     * Map the passed exception to an error message.
     * Any potential exception (such as business exception) requiring a special message should be mapped here as well.
     */
    public void error(Throwable e) {
        if (ExceptionUtil.isCausedBy(e, DataIntegrityViolationException.class)) {
            this.error("error_unique_constraint_violation");
        }
        else if (ExceptionUtil.isCausedBy(e, OptimisticLockingFailureException.class)) {
            this.error("error_concurrent_modification");
        }
        else if (ExceptionUtil.isCausedBy(e, AccessDeniedException.class)) {
            // works only if the spring security filter is before the exception filter, 
            // that is if the exception filter handles the exception first.
            this.error("error_access_denied");
        }
        else {
            this.error("status_exception_ko", getMessage(e));
            log.error("====> !!ATTENTION!! DEVELOPERS should provide a less generic error message for the cause of this exception <====");
        }
    }

    private String getMessage(Throwable e) {
        String message = e.getClass().getCanonicalName();
        Throwable current = e;
        while (current != null) {
            if (current.getMessage() != null && !current.getMessage().trim().isEmpty()) {
                message = current.getMessage();
            }
            current = current.getCause();
        }
        return message;
    }

    //endregion

    //region Construct Message

    private void addFacesMessage(FacesMessage fm) {
        if (fm != null) {
            FacesContext.getCurrentInstance().addMessage(null, fm);
        }
    }

    private void addFacesMessageUsingKey(Severity severity, String summaryKey, Object arg) {
        addFacesMessageUsingKey(severity, summaryKey, new Object[] { arg });
    }

    private void addFacesMessageUsingKey(Severity severity, String summaryKey, Object[] args) {
        addFacesMessage(newFacesMessageUsingKey(severity, summaryKey, args));
    }

    private void addFacesMessageUsingText(Severity severity, String text) {
        addFacesMessage(newFacesMessageUsingText(severity, text));
    }

    private FacesMessage newFacesMessageUsingKey(Severity severity, String summaryKey, Object[] args) {
        return newFacesMessageUsingText(severity, resourcesUtil.getProperty(summaryKey, args));
    }

    private FacesMessage newFacesMessageUsingText(Severity severity, String text) {
        FacesMessage fm = new FacesMessage(MessageUtil.toCssFriendly(severity), text);
        fm.setSeverity(severity);
        return fm;
    }

    //endregion

    //endregion

    //region Static

    public static String toCssFriendly(Severity severity) {
        if (severity.equals(SEVERITY_INFO)) {
            return "info";
        } else if (severity.equals(SEVERITY_WARN)) {
            return "warn";
        } else if (severity.equals(SEVERITY_ERROR)) {
            return "error";
        } else if (severity.equals(SEVERITY_FATAL)) {
            return "fatal";
        }

        throw new IllegalStateException("Unexpected message severity: " + severity.toString());
    }

    //endregion

}